FROM golang:1.22

# Postgres
ENV DBDRIVER=$DBDRIVER
ENV DATABASE_URI=$DATABASE_URI
ENV FORCE_MIGRATION=$FORCE_MIGRATION
ENV MIGRATION_URL=$MIGRATION_URL
# Aws
ENV ACCESS_KEY=$ACCESS_KEY
ENV SECRET_ACCESS_KEY=$SECRET_ACCESS_KEY
ENV S3_BUCKET=$S3_BUCKET
# Server
ENV SERVERPORT=$SERVERPORT
ENV SERVERENV=$SERVERENV
# Jwt
ENV JWTEXPIRE=$JWTEXPIRE
ENV JWTSECRET=$JWTSECRET
# Google
ENV MAPS_PLACES_API_KEY=$MAPS_PLACES_API_KEY
ENV MAPS_GEOCODE_API_KEY=$MAPS_GEOCODE_API_KEY
ENV MAPS_ROUTES_API_KEY=$MAPS_ROUTES_API_KEY
# Redis
ENV REDIS_ENDPOINT=$REDIS_ENDPOINT
# Ipinfo
ENV IPINFO_API_KEY=$IPINFO_API_KEY
# Paystack
ENV PAYSTACK_BASE_API=$PAYSTACK_BASE_API
ENV PAYSTACK_SECRET_KEY=$PAYSTACK_SECRET_KEY
# Pricer
ENV MINIMUM_HOURLY_WAGE=$MINIMUM_HOURLY_WAGE

RUN mkdir -p go/src/app
WORKDIR go/src/app
COPY . .
RUN go mod download && go mod verify
RUN CGO_ENABLED=0 GOOS=linux go build -o uzi-api

EXPOSE 8000

CMD ["./uzi-api"]
