// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package store

import (
	"net/netip"
	"time"

	"github.com/google/uuid"
)

type Session struct {
	ID        uuid.UUID
	Ip        netip.Addr
	Token     string
	Expires   int64
	UserID    uuid.NullUUID
	CreatedAt time.Time
	UpdatedAt time.Time
}

type User struct {
	ID        uuid.UUID
	FirstName string
	LastName  string
	Phone     string
	CreatedAt time.Time
	UpdatedAt time.Time
}
