// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: route.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createRoute = `-- name: CreateRoute :one
INSERT INTO routes (
  distance, trip_id, eta, state, polyline
) VALUES (
  $1, $2, $3, $4, ST_GeographyFromText($5)
)
RETURNING id, distance, polyline, eta, state, trip_id, created_at, updated_at
`

type CreateRouteParams struct {
	Distance string        `json:"distance"`
	TripID   uuid.NullUUID `json:"trip_id"`
	Eta      time.Time     `json:"eta"`
	State    string        `json:"state"`
	Polyline interface{}   `json:"polyline"`
}

func (q *Queries) CreateRoute(ctx context.Context, arg CreateRouteParams) (Route, error) {
	row := q.db.QueryRowContext(ctx, createRoute,
		arg.Distance,
		arg.TripID,
		arg.Eta,
		arg.State,
		arg.Polyline,
	)
	var i Route
	err := row.Scan(
		&i.ID,
		&i.Distance,
		&i.Polyline,
		&i.Eta,
		&i.State,
		&i.TripID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
