// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: vehicle.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createVehicle = `-- name: CreateVehicle :one
INSERT INTO vehicles (
  product_id, courier_id, mass
) VALUES (
  $1, $2, $3
)
RETURNING id, mass, product_id, courier_id, created_at, updated_at
`

type CreateVehicleParams struct {
	ProductID uuid.UUID     `json:"product_id"`
	CourierID uuid.NullUUID `json:"courier_id"`
	Mass      float64       `json:"mass"`
}

func (q *Queries) CreateVehicle(ctx context.Context, arg CreateVehicleParams) (Vehicle, error) {
	row := q.db.QueryRowContext(ctx, createVehicle, arg.ProductID, arg.CourierID, arg.Mass)
	var i Vehicle
	err := row.Scan(
		&i.ID,
		&i.Mass,
		&i.ProductID,
		&i.CourierID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
