package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.41

import (
	"context"

	"github.com/edwinlomolo/uzi-api/gql"
	"github.com/edwinlomolo/uzi-api/gql/model"
)

// User is the resolver for the user field.
func (r *courierResolver) User(ctx context.Context, obj *model.Courier) (*model.User, error) {
	return r.userService.FindUserByID(obj.UserID)
}

// Trip is the resolver for the trip field.
func (r *courierResolver) Trip(ctx context.Context, obj *model.Courier) (*model.Trip, error) {
	return r.tripService.GetTrip(obj.ID)
}

// Product is the resolver for the product field.
func (r *courierResolver) Product(ctx context.Context, obj *model.Courier) (*model.Product, error) {
	return r.GetCourierProduct(obj.ProductID)
}

// Courier returns gql.CourierResolver implementation.
func (r *Resolver) Courier() gql.CourierResolver { return &courierResolver{r} }

type courierResolver struct{ *Resolver }
