package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.41

import (
	"context"

	"github.com/edwinlomolo/uzi-api/gql"
	model1 "github.com/edwinlomolo/uzi-api/gql/model"
)

// Product is the resolver for the product field.
func (r *courierResolver) Product(ctx context.Context, obj *model1.Courier) (*model1.Product, error) {
	return r.GetCourierProduct(obj.ProductID)
}

// Courier returns gql.CourierResolver implementation.
func (r *Resolver) Courier() gql.CourierResolver { return &courierResolver{r} }

type courierResolver struct{ *Resolver }
