package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.41

import (
	"context"

	"github.com/3dw1nM0535/uzi-api/gql"
	"github.com/3dw1nM0535/uzi-api/gql/model"
)

// Trip is the resolver for the trip field.
func (r *recipientResolver) Trip(ctx context.Context, obj *model.Recipient) (*model.Trip, error) {
	return r.tripService.GetTrip(obj.TripID)
}

// Recipient is the resolver for the recipient field.
func (r *tripResolver) Recipient(ctx context.Context, obj *model.Trip) (*model.Recipient, error) {
	return r.tripService.GetTripRecipient(obj.ID)
}

// Recipient returns gql.RecipientResolver implementation.
func (r *Resolver) Recipient() gql.RecipientResolver { return &recipientResolver{r} }

// Trip returns gql.TripResolver implementation.
func (r *Resolver) Trip() gql.TripResolver { return &tripResolver{r} }

type recipientResolver struct{ *Resolver }
type tripResolver struct{ *Resolver }
